title: "My Resume"
email: "your-email@example.com"
description: "A resume built with Jekyll."
url: "http://your-username.github.io/my-resume-site"
baseurl: ""
twitter_username: "your-twitter-handle"
github_username: "your-github-username"
theme: minima